version: "3.9"
services:
  backend:
    build: .
    container_name: chatbot-api
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_storage:/app/chroma_storage

  frontend:
    build: .
    container_name: chatbot-frontend
    command: streamlit run dash_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - backend
